Repository Los-senior-leads/ProyectoLSL, pull requests merged in 2021-12, with the labels that each got.

#1 Login front-end
  angular.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.module.ts
  src/app/login/login/login.component.css
  src/app/login/login/login.component.html
  src/app/login/login/login.component.ts
  src/app/login/login/login.module.ts
  src/polyfills.ts
Labels: Size: M

#7 Edit label-button
  src/app/pages/escalaSalarial/tablaEscalaSalarial/tablaEscalaSalarial.component.html
Labels: Size: XS

#9 Feature/login users
  src/app/pages/edificios/edificios.module.ts
  src/app/pages/edificios/tablaEdificiosUsuarios/tablaEdificiosUsuarios.component.css
  src/app/pages/edificios/tablaEdificiosUsuarios/tablaEdificiosUsuarios.component.html
  src/app/pages/edificios/tablaEdificiosUsuarios/tablaEdificiosUsuarios.component.ts
  src/app/pages/edificios/tablaEdificiosUsuarios/tablaEdificiosUsuarios.module.ts
  src/app/pages/escalaSalarial/escalaSalarial.module.ts
  src/app/pages/escalaSalarial/tablaEsaclaSalarialUsuarios/tablaEsaclaSalarialUsuarios.component.css
  src/app/pages/escalaSalarial/tablaEsaclaSalarialUsuarios/tablaEsaclaSalarialUsuarios.component.html
  src/app/pages/escalaSalarial/tablaEsaclaSalarialUsuarios/tablaEsaclaSalarialUsuarios.component.ts
  src/app/pages/escalaSalarial/tablaEsaclaSalarialUsuarios/tablaEsaclaSalarialUsuarios.module.ts
  src/app/pages/unidadesAdministrativas/tablaUnidaddesAdmnistrativasUsuarios/tablaUnidaddesAdmnistrativasUsuarios.component.css
  src/app/pages/unidadesAdministrativas/tablaUnidaddesAdmnistrativasUsuarios/tablaUnidaddesAdmnistrativasUsuarios.component.html
  src/app/pages/unidadesAdministrativas/tablaUnidaddesAdmnistrativasUsuarios/tablaUnidaddesAdmnistrativasUsuarios.component.ts
  src/app/pages/unidadesAdministrativas/tablaUnidaddesAdmnistrativasUsuarios/tablaUnidaddesAdmnistrativasUsuarios.module.ts
  src/app/pages/unidadesAdministrativas/unidadesAdministrativas.module.ts
Labels: Size: M

#10 Navegacion para usuarios
  src/app/app.module.ts
  src/app/login/login.component.css
  src/app/login/login.component.html
  src/app/login/login.component.ts
  src/app/pages/edificios/edificios.module.ts
  src/app/pages/edificios/tablaEdificiosUsuarios/tablaEdificiosUsuarios.component.ts
  src/app/pages/escalaSalarial/escalaSalarial.module.ts
  src/app/pages/escalaSalarial/tablaEsaclaSalarialUsuarios/tablaEsaclaSalarialUsuarios.component.ts
  src/app/pages/escalaSalarial/tablaEsaclaSalarialUsuarios/tablaEsaclaSalarialUsuarios.module.ts
  src/app/pages/unidadesAdministrativas/tablaUnidaddesAdmnistrativasUsuarios/tablaUnidaddesAdmnistrativasUsuarios.component.ts
  src/app/pages/unidadesAdministrativas/tablaUnidaddesAdmnistrativasUsuarios/tablaUnidaddesAdmnistrativasUsuarios.module.ts
  src/app/pages/unidadesAdministrativas/unidadesAdministrativas.module.ts
  src/app/pagesUsers/edificiosUser/edificiosUser.component.css
  src/app/pagesUsers/edificiosUser/edificiosUser.component.html
  src/app/pagesUsers/edificiosUser/edificiosUser.component.ts
  src/app/pagesUsers/edificiosUser/edificiosUser.module.ts
  src/app/pagesUsers/escalaSalarialUser/escalaSalarialUser.component.css
  src/app/pagesUsers/escalaSalarialUser/escalaSalarialUser.component.html
  src/app/pagesUsers/escalaSalarialUser/escalaSalarialUser.component.ts
  src/app/pagesUsers/escalaSalarialUser/escalaSalarialUser.module.ts
  src/app/pagesUsers/organigramaUser/organigramaUser.component.css
  src/app/pagesUsers/organigramaUser/organigramaUser.component.html
  src/app/pagesUsers/organigramaUser/organigramaUser.component.ts
  src/app/pagesUsers/organigramaUser/organigramaUser.module.ts
  src/app/pagesUsers/pagesUsers.component.css
  src/app/pagesUsers/pagesUsers.component.html
  src/app/pagesUsers/pagesUsers.component.ts
  src/app/pagesUsers/pagesUsers.module.ts
  src/app/pagesUsers/unidadesAdministrativasUser/unidadesAdministrativasUser.component.css
  src/app/pagesUsers/unidadesAdministrativasUser/unidadesAdministrativasUser.component.html
  src/app/pagesUsers/unidadesAdministrativasUser/unidadesAdministrativasUser.component.ts
  src/app/pagesUsers/unidadesAdministrativasUser/unidadesAdministrativasUser.module.ts
Labels: Size: L

#12 bug creating escalas fixed
  flask/app.py
Labels: Size: L

#20 CRUD para usuarios con distintos permisos desde superUser
  flasksrc/__pycache__/app.cpython-39.pyc
  flasksrc/app.py
  src/app/app.module.ts
  src/app/login/login.component.html
  src/app/login/login.component.ts
  src/app/pagesSuperUser/crearUsuario/crear-usuario.service.spec.ts
  src/app/pagesSuperUser/crearUsuario/crear-usuario.service.ts
  src/app/pagesSuperUser/crearUsuario/crearUsuario.component.css
  src/app/pagesSuperUser/crearUsuario/crearUsuario.component.html
  src/app/pagesSuperUser/crearUsuario/crearUsuario.component.ts
  src/app/pagesSuperUser/crearUsuario/crearUsuario.module.ts
  src/app/pagesSuperUser/eliminarUsuario/eliminar-usuario.service.spec.ts
  src/app/pagesSuperUser/eliminarUsuario/eliminar-usuario.service.ts
  src/app/pagesSuperUser/eliminarUsuario/eliminarUsuario.component.css
  src/app/pagesSuperUser/eliminarUsuario/eliminarUsuario.component.html
  src/app/pagesSuperUser/eliminarUsuario/eliminarUsuario.component.ts
  src/app/pagesSuperUser/eliminarUsuario/eliminarUsuario.module.ts
  src/app/pagesSuperUser/infoUsuario/info-usuario.service.spec.ts
  src/app/pagesSuperUser/infoUsuario/info-usuario.service.ts
  src/app/pagesSuperUser/infoUsuario/infoUsuario.component.css
  src/app/pagesSuperUser/infoUsuario/infoUsuario.component.html
  src/app/pagesSuperUser/infoUsuario/infoUsuario.component.ts
  src/app/pagesSuperUser/infoUsuario/infoUsuario.module.ts
  src/app/pagesSuperUser/modificarUsuario/modificar-usuario.service.spec.ts
  src/app/pagesSuperUser/modificarUsuario/modificar-usuario.service.ts
  src/app/pagesSuperUser/modificarUsuario/modificarUsuario.component.css
  src/app/pagesSuperUser/modificarUsuario/modificarUsuario.component.html
  src/app/pagesSuperUser/modificarUsuario/modificarUsuario.component.ts
  src/app/pagesSuperUser/modificarUsuario/modificarUsuario.module.ts
  src/app/pagesSuperUser/pagesSuperUser.component.css
  src/app/pagesSuperUser/pagesSuperUser.component.html
  src/app/pagesSuperUser/pagesSuperUser.component.ts
  src/app/pagesSuperUser/pagesSuperUser.module.ts
  src/app/pagesSuperUser/tablaUsuarios/tabla-usuarios.service.spec.ts
  src/app/pagesSuperUser/tablaUsuarios/tabla-usuarios.service.ts
  src/app/pagesSuperUser/tablaUsuarios/tablaUsuarios.component.css
  src/app/pagesSuperUser/tablaUsuarios/tablaUsuarios.component.html
  src/app/pagesSuperUser/tablaUsuarios/tablaUsuarios.component.ts
  src/app/pagesSuperUser/tablaUsuarios/tablaUsuarios.module.ts
  src/app/pagesSuperUser/usuarios.ts
Labels: Size: L

#25 Develop
  flasksrc/contador.py
  flasksrc/generacionReportes.py
  graficoEmpresasEstado.png
  graficoEmpresasFechasDeCierre.png
  graficoEmpresasFechasDeCreacion.png
  tests/__pycache__/test_contador.cpython-310-pytest-6.2.5.pyc
  tests/test_contador.py
Labels: Size: M
